name: "Build and Lint"
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  frontend:
    name: "Frontend Build and Lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"
      - name: "Install dependencies"
        run: pnpm install
      - name: "Build"
        run: pnpm run build
      - name: "Run lint"
        run: pnpm run lint

  backend:
    name: "Backend Build and Lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/sabkuch?sslmode=disable"
      JWT_SECRET: "ci-dummy-jwt-secret-key-123456789"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "./backend/pnpm-lock.yaml"
      - name: "Install dependencies"
        run: pnpm install
      - name: "Build"
        run: pnpm run build
      - name: "Run lint"
        run: pnpm run lint
